server:
  port: 1234

spring:
  application:
    name: auth-api
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: coti
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: ALWAYS
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
